name: Automated deploy

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GPR_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - run: npm version $RELEASE_VERSION --git-tag-version false
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@NeuraLegion'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GPR_TOKEN }}
